test.js

feature: Add test file

---

package.json
server/index.js

- Didn't change too much. Changed most of the code back to original. Changed scripts to run on Heroku
---

Heroku feature #13

---

server/db/models/record.js
server/db/models/recordOrder.js

Models improvements

---

client/components/all-products.js
client/components/record.js
client/store/cart.js
client/store/user.js
server/index.js

started cart feature fix bug

---

client/components/navbar.js
client/routes.js

This is a change to make shop button go to all products.

Changes Shop navigation to all products

---

records.js

fixed nirvana pic link

---

records.js

misc: changes seed data - records price now in pennies

---

client/routes.js

bug: home route takes to user profile page

---

client/components/all-products.js
client/store/index.js
client/store/record.js

We refactored the code from the previous branch. Now it works! User is able to load all products from the all products page.

refactor: successfully get all products with redux

---

client/components/cart.js
client/components/record.js
client/store/cart.js
client/store/index.js
seedData/ordersData.js
seedData/recordOrderData.js
server/api/cart.js
server/api/index.js
server/auth/index.js
server/db/models/order.js
server/db/models/recordOrder.js

Refactor model changes

---

client/components/cart.js
client/components/record.js
client/store/cart.js
server/api/cart.js
server/api/cart.spec.js

Get cart redux #51

---

client/app.js
client/components/all-products.js
client/components/record.js
client/components/user-home.spec.js
package-lock.json
package.json
public/style.css

Added flexbox for all-records, yellow background color, brown album container

Feature style react record

---

client/components/record.js

I took out the extra code added from a merge conflict fix.

bug: fix merge conflict changes

---

client/components/all-products.js
client/components/order-history.js
client/components/order-history.spec.js
client/components/ordered-record.js
client/components/user-home.js
client/store/index.js
client/store/orders.js
client/store/record.js
server/api/cart.js
server/api/index.js
server/api/orders.js

it needs styling but it's done

Feat Order History Vertical Slice Done

---

client/components/record.js
client/store/cart.js
client/store/cart.spec.js
client/store/record.spec.js
package-lock.json

* [x ] added unit tests (or none needed)
added tests and cleaned up console logs

Tests for api route

---

client/components/order-history.js
client/components/record.js
client/components/record.spec.js
client/components/user-home.js
client/components/user-home.spec.js
client/store/cart.js
client/store/orders.js

- added react tests
- cleaned up code

Feature react tests

---

client/components/index.js
client/components/navbar.js
client/components/user-profile.js
client/components/user-profile.spec.js
client/routes.js
package-lock.json
package.json
public/style.css

Feature style nav

---

client/components/record.js
server/api/cart.js

feat: backend add to cart route

---

package.json
seed.js
seedData/ordersData.js
seedData/usersData.js
server/auth/google.js

1.
There was an issue with user logins when you could only login with new user successfuly from 4th time. 
The reason might be postgress does not reset user id correctly after using bulkCreate.
I have changed our seed script to not use bulkCreate and was not able to reproduce the issue yet.
2. 
We used to get validation error when signing up in w google when there was already a user with that email in the db. This fix makes it so the user is taken back to login screen instead.
---

Refactor seed script and google strategy

---

client/components/auth-form.js
package.json
seed.js
seedData/ordersData.js
seedData/usersData.js
server/auth/google.js

Style the login page 
Remove console logs from google.js
---

Styling login

---

client/store/cart.js

fix: change GET-CART to GOT-CART

---

.travis.yml

bug: travis debugging

---

client/components/navbar.js

Gita cart notification

---

client/components/cart.js
client/components/ordered-record.js
client/components/single-cart.js
client/store/cart.js
server/api/cart.js

Cart layout

---

client/components/cart.js
client/components/user-profile.js
server/auth/google.js

feat: load cart into store at login

---

server/api/cart.js

Fixes logged in user's remove from cart

bug: fix remove from cart api route
